name: Wechat Release Notify

on:
  release:
    types: [published]


jobs:
  notify_to_email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: New Wechat Client Release(${{ steps.extract_branch.outputs.branch }})
          to: wlx0812@gmail.com
          from: GitHub Actions
