name: Wechat Release Notify

on:
  release:
    types: [released]


jobs:
  notify_to_email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: New Wechat Client Release(${{GITHUB_REF_NAME}})
          to: wlx0812@gmail.com
          from: GitHub Actions
